---
- name: Install Python APT module
  ansible.builtin.apt:
    install_recommends: false
    force_apt_get: true
    package: python3-apt
    state: present
    update_cache: false

- name: Prepare APT repositories
  block:

    - name: Remove original Debian repositories file
      ansible.builtin.file:
        path: /etc/apt/sources.list
        state: absent

    - name: Add Debian repository
      ansible.builtin.apt_repository:
        install_python_apt: false
        filename: debian
        repo: deb http://ftp.pl.debian.org/debian {{ ansible_facts.distribution_release }} main contrib non-free non-free-firmware
        state: present
        update_cache: false

    - name: Add Debian updates repository
      ansible.builtin.apt_repository:
        install_python_apt: false
        filename: debian
        repo: deb http://ftp.pl.debian.org/debian {{ ansible_facts.distribution_release }}-updates main contrib non-free non-free-firmware
        state: present
        update_cache: false

    - name: Add Debian security repository
      ansible.builtin.apt_repository:
        install_python_apt: false
        filename: debian
        repo: deb http://security.debian.org {{ ansible_facts.distribution_release }}-security main contrib non-free non-free-firmware
        state: present
        update_cache: false

    - name: Remove paid Ceph repository
      ansible.builtin.apt_repository:
        install_python_apt: false
        filename: ceph
        repo: deb https://enterprise.proxmox.com/debian/ceph-quincy {{ ansible_facts.distribution_release }} enterprise
        state: absent
        update_cache: false

    - name: Add free Ceph repository
      ansible.builtin.apt_repository:
        install_python_apt: false
        filename: ceph
        repo: deb http://download.proxmox.com/debian/ceph-quincy {{ ansible_facts.distribution_release }} no-subscription
        state: present
        update_cache: false

    - name: Remove paid PVE repository
      ansible.builtin.apt_repository:
        install_python_apt: false
        filename: pve-enterprise
        repo: deb https://enterprise.proxmox.com/debian/pve {{ ansible_facts.distribution_release }} pve-enterprise
        state: absent
        update_cache: false

    - name: Add free PVE repository
      ansible.builtin.apt_repository:
        install_python_apt: false
        filename: pve-enterprise
        repo: deb http://download.proxmox.com/debian/pve {{ ansible_facts.distribution_release }} pve-no-subscription
        state: present
        update_cache: false

- name: Ensure APT cache is updated
  ansible.builtin.apt:
    cache_valid_time: 3600
    force_apt_get: true
    update_cache: true
  failed_when: false
  changed_when: false
