---
- name: Install
  ansible.builtin.apt:
    cache_valid_time: 3600
    install_recommends: false
    force_apt_get: true
    package: lshw
    state: present

- name: Get all PCI network devices
  ansible.builtin.command:
    cmd: lshw -class net -numeric -json
  register: __pci_net_devs
  changed_when: false

- name: Set PCI network devices fact
  ansible.builtin.set_fact:
    pci_network_devices: "{{ __pci_net_devs.stdout | from_json | json_query('[]') }}"
  changed_when: false

- debug:
    var: pci_network_devices

- name: Set vm.swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '0'
    state: present
    reload: true

- name: Install intel microcode
  ansible.builtin.apt:
    update-cache: true
    cache_valid_time: 3600
    install_recommends: false
    force_apt_get: true
    package: intel-microcode
    state: present
  notify: Reboot system

- name: Enable IOMMU
  ansible.builtin.lineinfile:
    path: /etc/kernel/cmdline
    regexp: '^(root=(?:(?!intel_iommu=on).)*?)$'
    line: '\1 intel_iommu=on'
    backup: true
    backrefs: true
  notify:
    - Update boot tool
    - Reboot system

- name: Enable passthrough
  ansible.builtin.lineinfile:
    path: /etc/kernel/cmdline
    regexp: '^(root=(?:(?!intel=pt).)*?)$'
    line: '\1 intel=pt'
    backup: true
    backrefs: true
  notify:
    - Update boot tool
    - Reboot system

- name: Enable bus assignment for all PCI devices
  ansible.builtin.lineinfile:
    path: /etc/kernel/cmdline
    regexp: '^(root=(?:(?!pci=assign-busses).)*?)$'
    line: '\1 pci=assign-busses'
    backup: true
    backrefs: true
  notify:
    - Update boot tool
    - Reboot system

#- name: Split PCIe devices into separate IOMMU groups
#  when: iommu_split_devices is defined
#  notify:
#    - Update boot tool
#    - Reboot system
#  block:
#
#    - name: Enable Access Control Services override for selected devices
#      ansible.builtin.lineinfile:
#        path: /etc/kernel/cmdline
#        regexp: '^(root=.*\s+pcie_acs_override=)\S+(.*)$'
#        line: '\1{{ ["id:"] | product(iommu_split_devices) | map("join") | list | join(",") }}\2'
#        backup: true
#        backrefs: true

- name: Ensure kernel modules will be loaded at boot
  ansible.builtin.template:
    src: modules.j2
    dest: /etc/modules
  notify:
    - Update initramfs
    - Reboot system

- name: cpufrequtils | install
  ansible.builtin.apt:
    cache_valid_time: 3600
    install_recommends: false
    force_apt_get: true
    package: cpufrequtils
    state: present

- name: cpufrequtils | configure
  ansible.builtin.lineinfile:
    path: /etc/init.d/cpufrequtils
    regexp: '^GOVERNOR='
    line: 'GOVERNOR="powersave"'
    backup: true
  notify:
    - cpufrequtils | reload
    - cpufrequtils | restart

- name: cpufrequtils | ensure service is reloaded
  ansible.builtin.meta: flush_handlers

- name: cpufrequtils | start and enable service
  ansible.builtin.service:
    name: cpufrequtils
    state: started
    enabled: true
