---
- name: systemd | reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: ansible_facts.service_mgr == "systemd"
  listen:
    - nginx | reload
    - cpufrequtils | reload

- name: nginx | reload
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: ansible_facts.service_mgr != "systemd"

- name: nginx | restart
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: cpufrequtils | reload
  ansible.builtin.service:
    name: cpufrequtils
    state: reloaded
  when: ansible_facts.service_mgr != "systemd"

- name: cpufrequtils | restart
  ansible.builtin.service:
    name: cpufrequtils
    state: restarted

- name: Update boot tool
  ansible.builtin.shell:
    cmd: proxmox-boot-tool refresh

- name: Update initramfs
  ansible.builtin.shell:
    cmd: update-initramfs -u -k all

- name: Reboot system
  ansible.builtin.reboot:
    reboot_timeout: 900
