---
- name: Install
  ansible.builtin.apt:
    cache_valid_time: 3600
    install_recommends: false
    force_apt_get: true
    package: vim
    state: present

- name: Configure
  ansible.builtin.template:
    src: vimrc.j2
    dest: /etc/vim/vimrc.local

